version: "3"
services:
  frontend:
    image: 1stzorua/biddygo:main
    ports:
      - "80:3000"
  backend:
    image: 1stzorua/biddygo:api
    ports:
      - "81:443"
    # depends_on: 
    #   - mongodb-db
    #   - mssql-db
  # mongodb-db:
  #   image: mongo:latest
  #   environment: 
  #     - MONGO_INITDB_DATABASE=biddygo
  #   ports:
  #     - "27017:27017"
  # mssql-db:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=6BM:8aFu^Mc,}e*
  #     - MSSQL_DB=biddygo
  #   ports:
  #     - "1433:1433"