name: cicd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
    - uses: actions/checkout@v4.0.0
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.8.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm test
      
  publish:
    needs: build_and_test
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
    - name: Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Metadata action
      id: meta
      uses: docker/metadata-action@v5.0.0
      with:
        images: 1stzorua/biddygo
    - name: Build and push images
      uses: docker/build-push-action@v5.0.0
      with: 
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
